### ISSUE TITLE
Foundations: Typography Content Refactor

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/dto-design-guide#25]
- [ ] Can we use code to generate the content of the `font-specimen.png`?
-  [ ] Need to fix links to right place in the SCSS.
- [ ] Final proof of content.

**Comment by joolswood** [comment]
Some of the issues I've picked up on:
- naming of examples separate from what is in the scss element
- pulling the example file from the md rather than the scss
- issue of repeating identical headings when a page contains multiple components (accessibility issue)
- need to be able to add principle prior between heading and rendered example (and between heading and in this section)
- capitalisation of `rendered example`
- still needing a scss entry even when the content on the page is just guidance

**Comment by joolswood** [comment]
Here's another weird one. Loading the `typography` page from the left menu only loads the scss content. I have to go to the `foundations` page then the `typography` page to get the md collections content!

**Comment by klepas** [comment]
Just updating this with the chats we had — all agreed that we want to make a range of changes; the points above from @joolswood are all valid.

For clarity, I proposed we make a list, side-by-side of the content that comes from both the md files in the dto-design-guide repo, and the SASS, such that we get a better grasp together what lives where, how things are slotted together, and what limitations currently exist in our templating, and then what edits we need to make.

**Comment by joolswood** [comment]
Mapping here: https://docs.google.com/spreadsheets/d/1Abn7vKhmrz8GA-DwwXniamD0lmgTI_KXCdntINny7Pc/edit#gid=965974777

**Comment by joolswood** [comment]
I've been working in the `feature/typography-refactor` branch. There's changes to the SCSS that are currently only on my local machine so I'll need to chat with @klepas to make sure they are pushed up before we merge.
