### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by AndrewArch** [AusDTO/dto-design-guide#28]
re [http://dto-design-guide.apps.staging.digital.gov.au/#accessibility](http://dto-design-guide.apps.staging.digital.gov.au/#accessibility)

Do we intend to get the components 'audited'? or is this referring to the 'DTO Design Guide' site?

Needs clarifying :)

Also worth mentioning that any issues arising during the use of the UI-Kit in the development of products should be fed back to the team for consideration and appropriate rectification.

**Comment by klepas** [comment]
We have been testing the components as they are used by other teams (those sessions you kindly organised Andrew).

I’m keen to close this issue since the a11y info is no longer on the readme/homepage — it’s been lifted and moved into *Getting started* > *For developers* > *Accessibility*, and I need to update this content (which is tracked in #58).
